### PR TITLE
 [ Fix ] restructured and restyled #find me

### LINKED ISSUE #1: Fix FIND ME HERE Section
Need to Fix FIND ME HERE section elements aligments. 
Fix space between Them.

### PR DESCRIPTION
**Pull request by kaustav202**
Made the necessary changes for better visibility and accessibility of find me section

fixes #1

### CODE REVIEW

**Comment by kaustav202** [comment]
@virendracarpenter you can review

**Comment by virendracarpenter** [comment]
@kaustav202 Great work, Ones check when we resize tabs, the next rows they are too close. don't add &nbsp

**Review by virendracarpenter — COMMENTED** [review]
Please try to remove &nbsp.

**Comment by kaustav202** [comment]
This is the best implementation we can do for spaces and margins without `&nbsp;` as github markdown compiler doesn't support any css styling at all so have to rely on html elements

**Pull request merged**
